/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "primary-container": "var(--color-primary-container)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-surface": "var(--color-on-surface)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-variant": "var(--color-surface-variant)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        tertiary: "var(--color-tertiary)",
        // MainEngine colors
        outline: "var(--color-outline)",
        "inverse-surface": "var(--color-inverse-surface)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        surface: "var(--color-surface)",
        background: "var(--color-background)",
        "on-background": "var(--color-on-background)",
        primary: "var(--color-primary)",
        error: "var(--color-error)",
        "inverse-primary": "var(--color-inverse-primary)",
        "on-primary": "var(--color-on-primary)",
        "on-tertiary": "var(--color-on-tertiary)",
      },
      fontFamily: {
        body: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          '"Liberation Sans"',
          "sans-serif",
        ],
        headline: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          '"Liberation Sans"',
          "sans-serif",
        ],
        label: [
          "ui-sans-serif",
          "system-ui",
          "-apple-system",
          '"Segoe UI"',
          "Roboto",
          '"Helvetica Neue"',
          "Arial",
          '"Noto Sans"',
          '"Liberation Sans"',
          "sans-serif",
        ],
      },
      fontSize: {
        "headline-md": ["24px", { lineHeight: "1.2", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.2", letterSpacing: "0.08em", fontWeight: "600" }],
        "status-label": ["14px", { lineHeight: "1.2", fontWeight: "500" }],
        "display-lg": ["48px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
