import React, { createContext, useContext, useState, useCallback } from "react";

const translations = {
  en: {
    // Navigation
    brand: "AURA MARINE",
    mainEngine: "Main Engine",
    engineSystems: "Engine Systems",
    navigation: "Navigation",
    alarms: "Alarms",
    trend: "Trend",
    nauticalCharts: "Nautical Charts",
    
    // Common
    search: "Search",
    settings: "Settings",
    account: "Account",
    searchPlaceholder: "Search systems, engines, alarms...",
    noResults: "No results found",
    recentSearches: "Recent Searches",
    popularSearches: "Popular Searches",
    general: "General",
    display: "Display",
    notifications: "Notifications",
    language: "Language",
    english: "English",
    chinese: "中文",
    theme: "Theme",
    lightMode: "Light Mode",
    darkMode: "Dark Mode",
    systemDefault: "System Default",
    about: "About",
    version: "Version",
    logout: "Logout",
    profile: "Profile",
    userName: "Captain Zhang",
    userRole: "Chief Engineer",
    userId: "ID: CE-2024-001",
    
    // Dashboard
    cctv: "CCTV Feed (Option)",
    cctv1: "CCTV 1",
    cctv2: "CCTV 2",
    cctv3: "CCTV 3",
    systemStatus: "System Status",
    systemOnline: "Operating Angle",
    cpuLoad: "CPU LOAD",
    voyageStatistics: "Voyage Statistics",
    currentConfiguration: "Current Configuration",
    rotationalControl: "Rotational Control",
    realTimeData: "REAL-TIME DATA",
    latLon: "LAT / LON",
    wind: "WIND",
    draft: "DRAFT",
    speedSog: "SPEED (SOG)",
    headingPitch: "HEADING / PITCH",
    activeAlarms: "ACTIVE ALARMS",
    vessel: "VESSEL A",
    lux75Series: "LUX-75 SERIES",
    knots: "kn",
    normal: "Normal",
    fireAlarms: "FIRE ALARMS",
    highBilgeLevel: "HIGH BILGE LEVEL",
    engineOverheat: "ENGINE OVERHEAT",
    
    // Main Engine
    engine1: "Engine 1",
    engine2: "Engine 2",
    engine3: "Engine 3",
    engine4: "Engine 4",
    gen1: "Gen 1",
    gen2: "Gen 2",
    rpm: "RPM",
    exhTemp: "EXH.TEMP",
    oilPress: "OIL PRESS",
    turbo: "TURBO",
    kRpm: "KRPM",
    powerOutput: "POWER OUTPUT",
    coolantTemp: "COOLANT TEMP",
    diagnosis: "DIAGNOSIS",
    optimal: "OPTIMAL",
    fuelRate: "Fuel Rate",
    torque: "Torque",
    load: "Load",
    engineSpeed: "ENGINE SPEED",
    lubeOilPress: "LUBE OIL PRESS",
    loadFactor: "LOAD FACTOR",
    kw: "kW",
    lh: "L/h",
    bar: "BAR",
    percent: "%",
    
    // Engine Systems
    dieselEngine1: "DIESEL ENGINE 1",
    dieselEngine2: "DIESEL ENGINE 2",
    dieselEngine3: "DIESEL ENGINE 3",
    dieselEngine4: "DIESEL ENGINE 4",
    lubrication: "LUBRICATION",
    cooling: "COOLING",
    fuel: "FUEL",
    airIntake: "AIR INTAKE",
    lubricationSystem: "LUBRICATION SYSTEM",
    coolingSystem: "COOLING SYSTEM",
    fuelSystem: "FUEL SYSTEM",
    airIntakeSystem: "AIR INTAKE SYSTEM",
    lubeOilTemp: "Lube Oil Temp",
    filterDiffPress: "Filter Diff Press",
    crankcasePress: "Crankcase Press",
    coolantPressure: "Coolant Pressure",
    seaWaterPressure: "Sea Water Pressure",
    fuelDeliveryPress: "Fuel Delivery Press",
    fuelTemp: "Fuel Temp",
    intakeManifoldPressLB: "Intake Manifold Press LB",
    intakeManifoldTempLBF: "Intake Manifold Temp LBF",
    barometricPress: "Barometric Press",
    operationStatus: "OPERATION STATUS",
    powerOutputLabel: "Power Output",
    oilTemp: "OIL TEMP",
    healthySystem: "Healthy System",
    standbyMode: "Standby Mode",
    coolantPress: "COOLANT PRESS",
    seaWaterPress: "SEA WATER PRESS",
    manifoldPressLB: "MANIFOLD PRESS LB",
    exhaustTemp: "EXHAUST TEMP",
    engineLoad: "ENGINE LOAD",
    
    // Alarms
    overspeed: "OVERSPEED",
    eStopStatus: "E-STOP STATUS",
    armed: "Armed",
    ready: "Ready",
    waterLevel: "WATER LEVEL",
    low: "LOW",
    leakageStatus: "LEAKAGE STATUS",
    detected: "DETECTED",
    clear: "Clear",
    ok: "OK",
    controlPower: "CONTROL POWER",
    online: "Online",
    activeAlarmsCount: "ACTIVE ALARMS",
    tapToAcknowledge: "Tap to acknowledge",
    noActiveAlarms: "No Active Alarms",
    aboveNominal: "ABOVE NOMINAL",
    nominal: "NOMINAL",
    attentionRequired: "Attention Required",
    allSystemsNormal: "All Systems Normal",
    requiresAttention: "alarm(s) require attention. Check diagnostic panel.",
    operatingNormally: "Engine operating within normal parameters.",
    
    // Trend
    diesel1: "Diesel 1",
    diesel2: "Diesel 2",
    auxGen1: "Aux Gen 1",
    auxGen2: "Aux Gen 2",
    cylinderTemperature: "Cylinder Temperature",
    thermalAnalysis: "THERMAL ANALYSIS: STEADY STATE",
    sensors: "SENSORS",
    active: "ACTIVE",
    deviation: "DEVIATION",
    threshold: "THRESHOLD",
    tempDeviation: "Temp Deviation",
    firingPressure: "Firing Pressure",
    lubOilPressure: "Lub Oil Pressure",
    vitalsNominal: "VITALS: NOMINAL",
    activeAlarmsZero: "0 ACTIVE ALARMS",
    maxExhTemp: "Max Exh Temp",
    minExhTemp: "Min Exh Temp",
    avgExhTemp: "Avg Exh Temp",
    tempDev: "Temp Deviation",
    turbochargerSpeed: "Turbocharger Speed",
    cylinder: "Cylinder",
    normalRange: "Normal range",
    stable: "Stable",
    warning: "Warning",
    loadOptimized: "Load Optimized",
    
    // Nautical Charts
    vesselA: "VESSEL A",
    systemOnline: "System: Online",
    emergencyStop: "EMERGENCY STOP",
    realTimeDataLabel: "REAL-TIME DATA",
    windSpeed: "Wind Speed",
    vesselHeading: "Vessel Heading",
    vitals: "VITALS",
    latitude: "Latitude",
    longitude: "Longitude",
    currentDraft: "Current Draft",
    activeAlarmsLabel: "ACTIVE ALARMS",
    critical: "CRITICAL",
    updatedAgo: "Updated 2s ago",
    localTime: "Local Time",
    speedOverGround: "Speed Over Ground",
    openChartDetails: "Open Chart Details",
    clickVessel: "Click on a vessel to view details",
    voyageProgress: "VOYAGE PROGRESS",
    departure: "Departure",
    eta: "ETA",
    arrival: "Arrival",
    fuelConsumption: "FUEL CONSUMPTION",
    optimalLabel: "Optimal",
    avgRate: "Avg Rate",
    efficiency: "Efficiency",
    enRoute: "En route",
    atAnchor: "At Anchor",
    maintenance: "Maintenance",
    zone: "Zone",
    fireDetection: "Fire Detection - Zone",
    mainEngineDeck: "Main Engine Deck",
    highBilge: "High Bilge Level",
    aftPumpRoom: "Aft Pump Room",
    filterMaintenance: "Filter Maintenance Due",
    scheduled: "Scheduled",

    // Configuration Parameters
    configParameters: "Configuration",
    displaySettings: "Display Settings",
    fullscreenMode: "Fullscreen Mode",
    dayNightMode: "Day / Night Mode",
    autoRotation: "Auto Rotation",
    envSync: "Environment & Sync",
    localConfig: "Local Configuration",
    cloudConfig: "Cloud Configuration",
    syncNow: "Sync Now",
    lastSynced: "Last synced",
    thresholdConfig: "Threshold Configurator",
    engineMetrics: "Engine Metrics",
    yellowWarningThreshold: "Yellow Warning Threshold",
    redAlarmThreshold: "Red Alarm Threshold",
    saveChanges: "Save Changes",
    resetDefaults: "Reset Defaults",
    savedSuccess: "Settings saved successfully",
    // AI & Trend
    fuelConsumptionCurve: "Fuel Consumption Curve",
    actualPowerCurve: "Actual Power Curve",
    multiDimensionalQuery: "Multi-dimensional Query",
    aiOptimization: "AI Optimization",
    askAISuggestion: "Ask AI for suggestions",
    energySavingTip: "Energy Saving Tip",
    optimalRPMAdvice: "Optimal RPM Advice",
    selectMetrics: "Select metrics to display",
    // 3D Model
    autoRotate3D: "Auto Rotate 3D",
    propulsionPower: "Propulsion Power",
    operatingAngle: "Operating Angle",
    // Alarms
    activeAlarmsList: "Active Alarms",
    alarmHistory: "Alarm History",
    searchFilters: "Search & Filters",
    filterAll: "All",
    filterUnacknowledged: "Unacknowledged",
    filterAcknowledged: "Acknowledged",
    filterResolved: "Resolved",
    acknowledgeAll: "Acknowledge All",
    clearAll: "Clear All",
    alarmSource: "Source",
    alarmTime: "Time",
    alarmPriority: "Priority",
    criticalPriority: "Critical",
    highPriority: "High",
    mediumPriority: "Medium",
    lowPriority: "Low",
    faultHighlight: "Fault Highlight",
    faultDetected: "Fault Detected",
    noFaultsDetected: "No Faults Detected",
  },
  zh: {
    // Navigation
    brand: "极光号",
    mainEngine: "主机",
    engineSystems: "发动机系统",
    navigation: "导航",
    alarms: "警报",
    trend: "趋势",
    nauticalCharts: "航海图",
    
    // Common
    search: "搜索",
    settings: "设置",
    account: "账户",
    searchPlaceholder: "搜索系统、发动机、警报...",
    noResults: "未找到结果",
    recentSearches: "最近搜索",
    popularSearches: "热门搜索",
    general: "通用",
    display: "显示",
    notifications: "通知",
    language: "语言",
    english: "English",
    chinese: "中文",
    theme: "主题",
    lightMode: "浅色模式",
    darkMode: "深色模式",
    systemDefault: "跟随系统",
    about: "关于",
    version: "版本",
    logout: "退出登录",
    profile: "个人资料",
    userName: "张船长",
    userRole: "轮机长",
    userId: "编号: CE-2024-001",
    
    // Dashboard
    cctv: "监控画面 (可选)",
    cctv1: "监控 1",
    cctv2: "监控 2",
    cctv3: "监控 3",
    systemStatus: "系统状态",
    systemOnline: "系统: 在线",
    cpuLoad: "CPU 负载",
    voyageStatistics: "航行统计",
    currentConfiguration: "当前配置",
    rotationalControl: "旋转控制",
    realTimeData: "实时数据",
    latLon: "纬度 / 经度",
    wind: "风向",
    draft: "吃水",
    speedSog: "航速 (对地)",
    headingPitch: "航向 / 纵倾",
    activeAlarms: "活动警报",
    vessel: "A 号船",
    lux75Series: "豪华-75系列",
    knots: "节",
    normal: "正常",
    fireAlarms: "火灾警报",
    highBilgeLevel: "高舱底水位",
    engineOverheat: "发动机过热",
    
    // Main Engine
    engine1: "发动机 1",
    engine2: "发动机 2",
    engine3: "发动机 3",
    engine4: "发动机 4",
    gen1: "发电机 1",
    gen2: "发电机 2",
    rpm: "转速",
    exhTemp: "排气温度",
    oilPress: "油压",
    turbo: "涡轮",
    kRpm: "千转/分",
    powerOutput: "功率输出",
    coolantTemp: "冷却液温度",
    diagnosis: "诊断",
    optimal: "最优",
    fuelRate: "燃油率",
    torque: "扭矩",
    load: "负载",
    engineSpeed: "发动机转速",
    lubeOilPress: "润滑油压",
    loadFactor: "负载系数",
    kw: "千瓦",
    lh: "升/时",
    bar: "巴",
    percent: "%",
    
    // Engine Systems
    dieselEngine1: "柴油发动机 1",
    dieselEngine2: "柴油发动机 2",
    dieselEngine3: "柴油发动机 3",
    dieselEngine4: "柴油发动机 4",
    lubrication: "润滑",
    cooling: "冷却",
    fuel: "燃油",
    airIntake: "进气",
    lubricationSystem: "润滑系统",
    coolingSystem: "冷却系统",
    fuelSystem: "燃油系统",
    airIntakeSystem: "进气系统",
    lubeOilTemp: "润滑油温度",
    filterDiffPress: "滤清器压差",
    crankcasePress: "曲轴箱压力",
    coolantPressure: "冷却液压力",
    seaWaterPressure: "海水压力",
    fuelDeliveryPress: "燃油供给压力",
    fuelTemp: "燃油温度",
    intakeManifoldPressLB: "进气歧管压力 L",
    intakeManifoldTempLBF: "进气歧管温度 L",
    barometricPress: "大气压力",
    operationStatus: "运行状态",
    powerOutputLabel: "功率输出",
    oilTemp: "油温",
    healthySystem: "系统健康",
    standbyMode: "待机模式",
    coolantPress: "冷却液压力",
    seaWaterPress: "海水压力",
    manifoldPressLB: "歧管压力 L",
    exhaustTemp: "排气温度",
    engineLoad: "发动机负载",
    
    // Alarms
    overspeed: "超速",
    eStopStatus: "急停状态",
    armed: "待命",
    ready: "就绪",
    waterLevel: "水位",
    low: "低",
    leakageStatus: "泄漏状态",
    detected: "检测到",
    clear: "正常",
    ok: "正常",
    controlPower: "控制电源",
    online: "在线",
    activeAlarmsCount: "活动警报",
    tapToAcknowledge: "点击确认",
    noActiveAlarms: "无活动警报",
    aboveNominal: "超出额定",
    nominal: "正常",
    attentionRequired: "需要关注",
    allSystemsNormal: "系统全部正常",
    requiresAttention: "个警报需要处理，请检查诊断面板。",
    operatingNormally: "发动机运行正常。",
    
    // Trend
    diesel1: "柴油机 1",
    diesel2: "柴油机 2",
    auxGen1: "辅助发电机 1",
    auxGen2: "辅助发电机 2",
    cylinderTemperature: "气缸温度",
    thermalAnalysis: "热分析: 稳态",
    sensors: "传感器",
    active: "活跃",
    deviation: "偏差",
    threshold: "阈值",
    tempDeviation: "温度偏差",
    firingPressure: "燃烧压力",
    lubOilPressure: "润滑油压",
    vitalsNominal: "体征: 正常",
    activeAlarmsZero: "0 活动警报",
    maxExhTemp: "最高排气温度",
    minExhTemp: "最低排气温度",
    avgExhTemp: "平均排气温度",
    tempDev: "温度偏差",
    turbochargerSpeed: "涡轮增压器转速",
    cylinder: "气缸",
    normalRange: "正常范围",
    stable: "稳定",
    warning: "警告",
    loadOptimized: "负载优化",
    
    // Nautical Charts
    vesselA: "A 号船",
    systemOnline: "系统: 在线",
    emergencyStop: "紧急停止",
    realTimeDataLabel: "实时数据",
    windSpeed: "风速",
    vesselHeading: "船首向",
    vitals: "生命体征",
    latitude: "纬度",
    longitude: "经度",
    currentDraft: "当前吃水",
    activeAlarmsLabel: "活动警报",
    critical: "严重",
    updatedAgo: "2秒前更新",
    localTime: "当地时间",
    speedOverGround: "对地航速",
    openChartDetails: "打开海图详情",
    clickVessel: "点击船舶查看详情",
    voyageProgress: "航行进度",
    departure: "出发",
    eta: "预计到达",
    arrival: "到达",
    fuelConsumption: "燃油消耗",
    optimalLabel: "最优",
    avgRate: "平均速率",
    efficiency: "效率",
    enRoute: "航行中",
    atAnchor: "锚泊中",
    maintenance: "维护中",
    zone: "区域",
    fireDetection: "火灾探测 - 区域",
    mainEngineDeck: "主机甲板",
    highBilge: "高舱底水位",
    aftPumpRoom: "舵机舱",
    filterMaintenance: "滤器维护到期",
    scheduled: "已计划",

    // Configuration Parameters
    configParameters: "配置参数",
    displaySettings: "显示设置",
    fullscreenMode: "全屏模式",
    dayNightMode: "日间/夜间模式",
    autoRotation: "自动旋转",
    envSync: "环境与同步",
    localConfig: "本地配置",
    cloudConfig: "云端配置",
    syncNow: "立即同步",
    lastSynced: "上次同步",
    thresholdConfig: "阈值配置器",
    engineMetrics: "发动机指标",
    yellowWarningThreshold: "黄色警告阈值",
    redAlarmThreshold: "红色报警阈值",
    saveChanges: "保存更改",
    resetDefaults: "恢复默认",
    savedSuccess: "设置保存成功",
    // AI & Trend
    fuelConsumptionCurve: "燃油消耗曲线",
    actualPowerCurve: "实际功率曲线",
    multiDimensionalQuery: "多维查询",
    aiOptimization: "AI优化",
    askAISuggestion: "询问AI建议",
    energySavingTip: "节能提示",
    optimalRPMAdvice: "最优转速建议",
    selectMetrics: "选择要显示的指标",
    // 3D Model
    autoRotate3D: "自动旋转3D",
    propulsionPower: "推进功率",
    operatingAngle: "操作角度",
    // Alarms
    activeAlarmsList: "活动警报",
    alarmHistory: "警报历史",
    searchFilters: "搜索与筛选",
    filterAll: "全部",
    filterUnacknowledged: "未确认",
    filterAcknowledged: "已确认",
    filterResolved: "已解决",
    acknowledgeAll: "全部确认",
    clearAll: "全部清除",
    alarmSource: "来源",
    alarmTime: "时间",
    alarmPriority: "优先级",
    criticalPriority: "紧急",
    highPriority: "高",
    mediumPriority: "中",
    lowPriority: "低",
    faultHighlight: "故障高亮",
    faultDetected: "检测到故障",
    noFaultsDetected: "未检测到故障",
  },
};

const LanguageContext = createContext();

export const LanguageProvider = ({ children, language, setLanguage }) => {
  const t = translations[language] || translations.en;
  
  const value = {
    t,
    language,
    setLanguage,
    translations: translations[language],
  };
  
  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
};

export { translations };
